export const GENERATED_BUCKET_APPENDS = {
  "superhero": [
    "aging superhero",
    "america",
    "anti villain",
    "based on novel or book",
    "book",
    "book burning",
    "book comes to life",
    "book of the dead",
    "book signing",
    "child hero",
    "comic book shop",
    "dark hero",
    "dark secret",
    "dc extended universe (dceu)",
    "dissociative identity disorder",
    "dual identity",
    "fake identity",
    "female hero",
    "female superhero",
    "female villain",
    "hero",
    "heroic",
    "heroic mission",
    "heroine",
    "heroism",
    "identity",
    "identity crisis",
    "kryptonite",
    "legendary hero",
    "marvel cinematic universe (mcu)",
    "masked superhero",
    "masked supervillain",
    "master villain",
    "mistaken identity",
    "reluctant hero",
    "secret",
    "secret agent",
    "secret base",
    "secret code",
    "secret door",
    "secret formula",
    "secret government agency",
    "secret government organization",
    "secret history",
    "secret life",
    "secret organization",
    "secret passage",
    "secret past",
    "secret service",
    "secret society",
    "secret world",
    "sidekick",
    "spider",
    "spider bite",
    "stronger villain",
    "super hero girls",
    "super power",
    "supergirl",
    "superhero family",
    "superhero team",
    "superhero teamup",
    "superhuman abilities",
    "symbiote",
    "teen superhero",
    "teenage hero",
    "the conjuring universe",
    "top secret project",
    "tragic hero",
    "u.s. secret service agent",
    "universe",
    "vigilante justice",
    "villain",
    "villainess",
    "washington dc, usa",
    "wonder"
  ],
  "sci_fi_tech": [
    "advanced technology",
    "alien abduction",
    "alien contact",
    "alien friendship",
    "alien life-form",
    "alien monster",
    "alien planet",
    "alien race",
    "alien spaceship",
    "alien technology",
    "alternate dimension",
    "android horror",
    "artificial intelligence (a.i.)",
    "astronomy",
    "back in time",
    "british intelligence",
    "central intelligence agency (cia)",
    "changing the past or future",
    "clones",
    "colony",
    "computer",
    "computer hacker",
    "computer program",
    "computer screen",
    "computer simulation",
    "computer virus",
    "cosmic",
    "cosmos",
    "cyber terrorism",
    "dark future",
    "deadly planet",
    "deep space",
    "destruction of planet",
    "digital technology",
    "distant future",
    "drone",
    "dystopian sci-fi",
    "emotional intelligence",
    "engineering",
    "evil alien",
    "evil robot",
    "exploding planet",
    "exploration",
    "extraterrestrial technology",
    "favourite time",
    "female cyborg",
    "future",
    "galaxy",
    "genetic experiment",
    "genetic memory",
    "giant robot",
    "high technology",
    "history and technology",
    "hologram",
    "human android relationship",
    "humans and technology",
    "information technology",
    "intelligence",
    "intelligence agency",
    "intelligence officer",
    "invasion",
    "invisibility",
    "killer robot",
    "laboratory",
    "lunar mission",
    "machine",
    "machine town",
    "mad scientist",
    "man vs machine",
    "massachusetts institute of technology (mit)",
    "mechanical engineering",
    "meteor",
    "meteor crash",
    "mission",
    "moon",
    "mutant animal",
    "nasa",
    "nazi invasion",
    "near future",
    "new technology",
    "nuclear launch codes",
    "nuclear missile",
    "nuclear radiation",
    "nuclear submarine",
    "nuclear threat",
    "nuclear weapons",
    "opera",
    "parallel world",
    "planet",
    "planet earth",
    "planet invasion",
    "planet mars",
    "plutonium",
    "portal",
    "post-apocalyptic future",
    "primitive time",
    "quantum mechanics",
    "race against time",
    "radiation",
    "radioactive object or substance",
    "rescue mission",
    "research laboratory",
    "research scientist",
    "robot boy",
    "robot cop",
    "robot dinosaur",
    "robot suits",
    "satellite",
    "save the planet",
    "science and technology",
    "science goes awry",
    "scientist",
    "secret intelligence service",
    "secret mission",
    "space",
    "space invasion",
    "space mission",
    "space probe",
    "space race",
    "space research",
    "space vessel",
    "space walk",
    "spacecraft accident",
    "spacecraft officer",
    "spaceship crash",
    "starship",
    "super computer",
    "synthetic android",
    "technology",
    "teleportation",
    "time",
    "time bomb",
    "time freeze",
    "time manipulation",
    "time paradox",
    "time travel",
    "time warp",
    "transforming robot",
    "travel",
    "universe",
    "vienna opera",
    "voyage",
    "warp engine",
    "warp speed",
    "washing machine"
  ],
  "horror": [
    "android horror",
    "animal horror",
    "apocalypse",
    "bloodbath",
    "body horror",
    "christmas spirit",
    "creepy",
    "creepy doll",
    "creepy faces",
    "creepy person",
    "demonic",
    "dracula",
    "evil spirits",
    "folk horror",
    "frankenstein",
    "ghost child",
    "ghost hunting",
    "ghosts of the past",
    "gothic horror",
    "haunted by the past",
    "haunted mansion",
    "holiday horror",
    "horror anthology",
    "horror filmmaking",
    "horror for children",
    "horror parody",
    "horror spoof",
    "low-budget horror",
    "macabre",
    "mind possession",
    "monster horror",
    "nightmares",
    "nosferatu",
    "occult detective",
    "psychological horror",
    "revenge horror",
    "revenge slasher",
    "spooky",
    "supernatural horror",
    "survival horror",
    "teen slasher",
    "undead",
    "van helsing",
    "fear of death",
    "fear of change",
    "anxiety",
    "anxious",
    "scared",
    "frightened",
    "horrified",
    "suspicion",
    "suspicious",
    "distressing",
    "panic"
  ],
  "monster": [
    "alien monster",
    "beast",
    "caribbean sea",
    "creature",
    "creature attack",
    "cyclops",
    "deadly creature",
    "deep sea",
    "kraken",
    "magical creature",
    "megalodon",
    "monster horror",
    "monster island",
    "monster movie",
    "monster truck",
    "mummy",
    "mutant",
    "mutant animal",
    "mythical creature",
    "ogre",
    "prehistoric creature",
    "robot dinosaur",
    "sea",
    "sea pirates",
    "sea turtle",
    "spider",
    "tentacle",
    "water monster",
    "wolfman",
    "yeti"
  ],
  "war": [
    "afghanistan war (2001-2021)",
    "air force base",
    "american civil war",
    "american soldiers",
    "ancient warfare",
    "anti war protest",
    "battle axe",
    "battle of midway",
    "battle of thermopylae",
    "black soldier",
    "british army",
    "british navy",
    "civil war veteran",
    "cold war",
    "combat",
    "combat drone",
    "cuban missile crisis",
    "d-day",
    "desert battle",
    "epic battle",
    "eve of world war ii",
    "ex soldier",
    "female soldier",
    "fish tank",
    "french army",
    "future war",
    "german soldier",
    "irish army",
    "kamikaze",
    "mafia war",
    "mariana trench",
    "marine",
    "marine biologist",
    "marine corps",
    "military academy",
    "military base",
    "military officer",
    "military operation",
    "military service",
    "military unit",
    "military uprising",
    "missile",
    "mission",
    "naval battle",
    "naval combat",
    "naval warfare",
    "nuclear war",
    "one man army",
    "pacific war",
    "paratrooper",
    "post civil war",
    "post war germany",
    "post war japan",
    "post world war ii",
    "prisoner of war",
    "raf",
    "revolutionary war",
    "royal air force",
    "royal navy",
    "sea battle",
    "second sino-japanese war (1937-45)",
    "soldiers",
    "space battle",
    "space war",
    "spanish civil war (1936-39)",
    "sparta",
    "spartans",
    "star wars",
    "super soldier",
    "sword battle",
    "tank",
    "troops",
    "turkish army",
    "u.s. army ranger",
    "u.s. army soldier",
    "u.s. marine",
    "u.s. navy",
    "u.s. soldier",
    "us army",
    "us military",
    "vietnam veteran",
    "war crimes",
    "war game",
    "war horse",
    "war on drugs",
    "war on terror",
    "war orphan",
    "war veteran",
    "warhead",
    "weapon of mass destruction",
    "world war iii"
  ],
  "crime": [
    "accused of murder",
    "alien abduction",
    "art heist",
    "assassins",
    "bad cop",
    "bag of money",
    "bank",
    "bank job",
    "bank teller",
    "blackmail",
    "bratva (russian mafia)",
    "brutal murder",
    "buddy cop",
    "child abduction",
    "child kidnapping",
    "child murder",
    "chinese mafia",
    "cia",
    "cold blooded killer",
    "cop",
    "copycat killer",
    "corrupt cop",
    "corrupt judge",
    "corruption",
    "court",
    "court case",
    "crime boss",
    "crime epic",
    "crime family",
    "crime fighter",
    "crime gone awry",
    "crime lord",
    "crime scene",
    "crime scene investigation",
    "crime spree",
    "criminal gang",
    "criminal lawyer",
    "criminal mastermind",
    "criminal organization",
    "criminal underworld",
    "crooked cop",
    "dirty cop",
    "disbelieving cop",
    "drug",
    "drug deal",
    "drug lord",
    "drug mule",
    "drug rehabilitation",
    "drug usage",
    "ex-cop",
    "father murder",
    "fbi agent",
    "female assassin",
    "framed for a crime",
    "framed for murder",
    "french police",
    "gang of thieves",
    "gang rape",
    "gang violence",
    "gold heist",
    "heist gone wrong",
    "hired killer",
    "homicide detective",
    "homicide investigation",
    "interpol",
    "irish mob",
    "italian mafia",
    "japanese mafia",
    "judge",
    "kgb",
    "killer",
    "killer couple",
    "killer doll",
    "killer toys",
    "law enforcement",
    "lawyer",
    "lost money",
    "mafia family",
    "mafia war",
    "masked killer",
    "mass murder",
    "met police",
    "mi6",
    "mission of murder",
    "mob boss",
    "mob-lynching",
    "mobster",
    "money",
    "money transfer",
    "mossad",
    "motorcycle cop",
    "murder by gunshot",
    "murder mystery",
    "murder of father",
    "murder spree",
    "murder suspect",
    "murder trial",
    "mysterious killer",
    "nypd",
    "pirate gang",
    "police",
    "police coverup",
    "police dog",
    "police helicopter",
    "police officer",
    "police operation",
    "police procedural",
    "police profiling",
    "police scanner",
    "police siege",
    "police station",
    "police training",
    "police vigilantism",
    "ponzi scheme",
    "pretended murder",
    "professional assassin",
    "prosecutor",
    "public murder",
    "retired assassin",
    "rookie cop",
    "sadistic killer",
    "safecracker",
    "scammer",
    "sicilian mafia",
    "stalked by a killer",
    "state police",
    "stolen money",
    "street gang",
    "synthetic drug",
    "teenage killer",
    "theft",
    "thief",
    "tough cop",
    "treasure heist",
    "undercover cop",
    "zodiac killer"
  ],
  "violence": [
    "assault",
    "atomic bomb",
    "atomic bomb test",
    "beating",
    "bloody death",
    "bloody deaths",
    "bloody fight",
    "bomb",
    "bomb remote detonator",
    "bomb shelter",
    "bomb squad",
    "bomb vest",
    "brutal death",
    "brutal murder",
    "brutal violence",
    "cannibal",
    "combat",
    "cruelty",
    "decapitation",
    "driveby shooting",
    "explosions",
    "fight",
    "fight to the death",
    "fistfight",
    "gang violence",
    "graphic violence",
    "gun",
    "gun fight",
    "gun violence",
    "guns",
    "handgun",
    "knife",
    "laser gun",
    "martial arts tournament",
    "mixed martial arts (mma)",
    "multiple stabbings",
    "officer involved shooting",
    "police brutality",
    "prison fight",
    "rifle",
    "sexual violence",
    "sniper rifle",
    "strangulation",
    "street shootout",
    "sword fight",
    "terrorist bombing",
    "violence against animals",
    "violent death",
    "violent husband"
  ],
  "sex": [
    "adultery",
    "bondage",
    "cheating",
    "childhood sexual abuse",
    "femme fatale",
    "intimate",
    "killed during sex",
    "pornographic video",
    "prostitute",
    "same sex relationship",
    "seduction",
    "sex abuse",
    "sex offender",
    "sex scandal",
    "sexual abuse",
    "sexual frustration",
    "sexual identity",
    "sexual violence"
  ],
  "nudity": [
    "nude swimming"
  ],
  "drugs": [
    "addiction",
    "alcohol",
    "alcoholic",
    "alcoholic father",
    "alcoholic mother",
    "alcoholism",
    "drug",
    "hallucinogen",
    "lsd",
    "marijuana",
    "opium",
    "pill",
    "pills",
    "sobriety",
    "taking drugs",
    "war on drugs"
  ],
  "discrimination": [
    "anti-racism",
    "apartheid",
    "bigotry",
    "caste system",
    "ethnic diversity",
    "freedom of speech",
    "gender discrimination",
    "hate",
    "racial discrimination",
    "rage and hate",
    "slavery",
    "speech",
    "white supremacy"
  ],
  "mature": [
    "abuse of power",
    "assault",
    "childhood sexual abuse",
    "death of husband",
    "death of wife",
    "gang rape",
    "grieving",
    "grieving father",
    "grieving widower",
    "intergenerational trauma",
    "male rape",
    "miscarriage",
    "miscarriage of justice",
    "mourning",
    "prisoner abuse",
    "psychological",
    "psychological profiling",
    "psychopath",
    "psychotic",
    "rape culture",
    "rape revenge",
    "sex abuse",
    "sexual abuse",
    "sexual violence",
    "substance abuse",
    "suicide attempt",
    "suicide by hanging",
    "violence"
  ],
  "supernatural": [
    "angel",
    "christmas spirit",
    "deal with the devil",
    "demonic possession",
    "devil",
    "devil worship",
    "devil's son",
    "evil spirits",
    "fallen angel",
    "lucifer",
    "mind possession",
    "mysticism",
    "necro",
    "necronomicon",
    "oracle",
    "pact with the devil",
    "paranormal phenomena",
    "prophecy",
    "prophet",
    "reincarnation",
    "religion and supernatural",
    "resurrection",
    "school of witchcraft",
    "shapeshifting",
    "summoned",
    "supernatural creature",
    "supernatural horror",
    "supernatural phenomena",
    "supernatural power",
    "supernatural thriller",
    "telekinesis",
    "telepathy",
    "voodoo"
  ],
  "historical": [
    "1800s",
    "1860s",
    "1880s",
    "1890s",
    "1900s",
    "1910s",
    "2000s",
    "ancient evil",
    "ancient world",
    "based on cartoon",
    "based on comic",
    "based on comic strip",
    "based on manga",
    "based on movie",
    "based on toy",
    "british empire",
    "egypt",
    "empire",
    "empire state building",
    "era",
    "greece",
    "historical artifacts",
    "historical event",
    "historical fiction",
    "historical figure",
    "italian renaissance",
    "medieval france",
    "ottoman",
    "renaissance painting",
    "roman catholic church",
    "sparta greece"
  ],
  "fairytale": [
    "animal kingdom",
    "based on fairy tale",
    "crown prince",
    "evil prince",
    "fairy",
    "forest",
    "modern fairy tale",
    "tooth fairy",
    "toy comes to life",
    "toymaker",
    "united kingdom"
  ],
  "fantasy_magic": [
    "arthur",
    "arthurian mythology",
    "based on myths, legends or folklore",
    "black magic",
    "camelot",
    "dark",
    "dark pact",
    "dark past",
    "dwarf",
    "egyptian mythology",
    "elves",
    "excalibur",
    "fantasy comedy",
    "fantasy creature",
    "fantasy sequence",
    "fantasy world",
    "fear of the dark",
    "goblin",
    "king arthur",
    "magic land",
    "magic mushroom",
    "magic realism",
    "magic spell",
    "norse god",
    "reality vs fantasy",
    "santa's elves",
    "sorceress",
    "sorcery",
    "sword",
    "sword and sandal",
    "sword and shield",
    "teen fantasy",
    "troll",
    "unicorn",
    "wizardry",
    "wuxia"
  ],
  "thriller_suspense": [
    "action thriller",
    "british spy",
    "cat and mouse",
    "child kidnapping",
    "comedy thriller",
    "conspiracy theory",
    "corporate conspiracy",
    "countdown",
    "cover-up",
    "female spy",
    "held hostage",
    "hostage situation",
    "international manhunt",
    "invasion",
    "legal thriller",
    "liberation of hostage",
    "on the run",
    "paranoia",
    "plot twist",
    "psychological",
    "psychological thriller",
    "revenge thriller",
    "russian spy",
    "spy",
    "supernatural thriller",
    "survival thriller",
    "suspense mystery",
    "tense",
    "tension",
    "unknown number",
    "woman spy"
  ],
  "mystery_detective": [
    "amateur detective",
    "clue",
    "covered investigation",
    "crime scene investigation",
    "cryptic",
    "detective",
    "detective story",
    "forensic",
    "forensic expert",
    "former detective",
    "french detective",
    "french inspector",
    "future noir",
    "hidden clues",
    "homicide detective",
    "homicide investigation",
    "inspector",
    "investigator",
    "locked room mystery",
    "murder mystery",
    "neo-noir",
    "occult detective",
    "police detective",
    "private",
    "private contractor",
    "riddle",
    "suspense mystery",
    "tech noir",
    "unreliable narrator"
  ],
  "romance_love": [
    "abusive relationship",
    "arguing couple",
    "arranged marriage",
    "aunt nephew relationship",
    "aunt niece relationship",
    "beach wedding",
    "best friend's wedding",
    "boys' love (bl)",
    "break-up",
    "brother brother relationship",
    "brother sister relationship",
    "cheat on husband",
    "clueless husband",
    "co-workers relationship",
    "controlling wife",
    "dark romance",
    "dating",
    "death of lover",
    "destination wedding",
    "dysfunctional relationship",
    "employer employee relationship",
    "everlasting love",
    "ex-girlfriend",
    "ex-husband ex-wife relationship",
    "ex-lover",
    "father daughter relationship",
    "father son relationship",
    "female lover",
    "fictitious marriage",
    "first love",
    "former lovers",
    "fugitive lovers",
    "girls' love (gl)",
    "gothic romance",
    "grandfather granddaughter relationship",
    "grandfather grandson relationship",
    "heartbreak",
    "honeymoon",
    "human android relationship",
    "human animal relationship",
    "husband wife relationship",
    "imminent wedding",
    "interracial romance",
    "kiss",
    "love",
    "love at first sight",
    "love of one's life",
    "love on the run",
    "lover",
    "lovers",
    "manipulative lover",
    "marriage",
    "marriage crisis",
    "married couple",
    "master servant relationship",
    "missing wife",
    "mother daughter relationship",
    "mother son relationship",
    "neighbor neighbor relationship",
    "odd couple",
    "paralytic husband",
    "parent child relationship",
    "past relationship",
    "platonic love",
    "power of love",
    "reincarnated lovers",
    "relationship problems",
    "relationship sabotage",
    "romantic dramedy",
    "same sex relationship",
    "secretive wife",
    "sibling relationship",
    "sister sister relationship",
    "soulmates",
    "star crossed lovers",
    "teacher student relationship",
    "teenage love",
    "teenage romance",
    "toxic relationship",
    "tragic love",
    "tragic romance",
    "unexpected romance",
    "unfulfilled love",
    "wedding",
    "wife",
    "young couple"
  ],
  "comedy_humor": [
    "action comedy",
    "adventure comedy",
    "black humor",
    "buddy comedy",
    "caper comedy",
    "comedy of situation",
    "comedy thriller",
    "crude humor",
    "dark",
    "family comedy",
    "fantasy comedy",
    "goofy",
    "hilarious",
    "horror parody",
    "horror spoof",
    "mockumentary",
    "quirky comedy",
    "religious satire",
    "ridiculous",
    "sarcastic",
    "sardonic",
    "shaggy dog story",
    "slapstick comedy",
    "social satire",
    "stand-up comedy"
  ],
  "drama_family": [
    "abusive family",
    "abusive mother",
    "adopted daughter",
    "adopted son",
    "adoption",
    "adoptive father",
    "alien friendship",
    "animal human friendship",
    "avenging father",
    "bad parenting",
    "based on young adult novel",
    "big family",
    "boarding school",
    "boys' school",
    "brother",
    "brother against brother",
    "brother and sister",
    "brother-in-law",
    "childhood",
    "childhood friends",
    "childhood memory",
    "childhood sweetheart",
    "chosen family",
    "college",
    "college graduate",
    "college professor",
    "college student",
    "conflict",
    "courtroom drama",
    "crime family",
    "danger of life",
    "daughter",
    "dead daughter",
    "dead father",
    "dead parent",
    "death in family",
    "death of brother",
    "death of family",
    "death of father",
    "death of mother",
    "divorce",
    "dog man friendship",
    "domineering mother",
    "dysfunctional family",
    "enduring friendship",
    "english teacher",
    "estranged son",
    "eternal youth",
    "expectant mother",
    "family clan",
    "family comedy",
    "family dog",
    "family dynamics",
    "family history",
    "family holiday",
    "family in peril",
    "family life",
    "family problems",
    "family relationships",
    "family reunion",
    "family secrets",
    "family vacation",
    "father",
    "father and child",
    "father daughter estrangement",
    "father son conflict",
    "father son reunion",
    "female friendship",
    "foster family",
    "foster sister",
    "found family",
    "fountain of youth",
    "generations conflict",
    "girls' school",
    "half-brother",
    "high school",
    "high school classmates",
    "high school reunion",
    "high school student",
    "homosexual father",
    "ill mother",
    "immigrant family",
    "interracial friendship",
    "interspecies friendship",
    "jewish family",
    "joy of life",
    "katanga conflict",
    "law student",
    "legal drama",
    "loss and grief",
    "loss of child",
    "loss of loved one",
    "loss of mother",
    "loss of wife",
    "mafia family",
    "male female friendship",
    "male friendship",
    "medical student",
    "mentor",
    "middle school",
    "missing daughter",
    "missing mother",
    "missing son",
    "mother",
    "mother and daughter",
    "mother and son",
    "mother daughter reunion",
    "mother son estrangement",
    "new family",
    "new school",
    "orphan",
    "overprotective mother",
    "protective father",
    "psychological drama",
    "rebellious daughter",
    "royal family",
    "school",
    "school bus",
    "school class",
    "school friend",
    "school play",
    "school project",
    "separation from family",
    "short-term memory loss",
    "single father",
    "single mother",
    "single parent",
    "sister",
    "sister-in-law",
    "student",
    "superhero family",
    "teacher",
    "teachers and students",
    "teenage daughter",
    "teenage student",
    "teenager",
    "traditional family",
    "turkish family",
    "twin brother",
    "unlikely friendship",
    "widowed mother",
    "young adult"
  ],
  "action_adventure": [
    "action comedy",
    "action hero",
    "action packed",
    "action thriller",
    "adventure comedy",
    "bulletproof car",
    "buried treasure",
    "car",
    "car accident",
    "car bomb",
    "car crash",
    "car fire",
    "car mechanic",
    "car race",
    "cgi-live action hybrid",
    "child driving car",
    "children's adventure",
    "civil action",
    "escape artist",
    "escape plan",
    "escape room",
    "explorer",
    "fast car",
    "flying car",
    "foot chase",
    "globetrotting adventure",
    "helicopter chase",
    "hit by a car",
    "hunt",
    "hunting",
    "indonesian action",
    "job hunting",
    "killed in action",
    "live action and animation",
    "live action remake",
    "living in car",
    "lost treasure",
    "martial artist",
    "martial law",
    "mission",
    "motorcycle chase",
    "no escape",
    "oceanic expedition",
    "odyssey",
    "parkour",
    "part live action",
    "pirate",
    "pirate ship",
    "police chase",
    "prison escape",
    "rail car",
    "rescue",
    "rescue operation",
    "rescue team",
    "showdown",
    "space adventure",
    "stuntman",
    "survival",
    "treasure"
  ],
  "animation_kids": [
    "3d animation",
    "based on cartoon",
    "based on children's book",
    "cartoon elephant",
    "child protagonist",
    "children cartoon",
    "children in danger",
    "children's adventure",
    "children's author",
    "children's perspectives",
    "computer animation",
    "dead children",
    "desire to have children",
    "family",
    "foster kid",
    "helping children",
    "horror for children",
    "kid genius",
    "live action and animation",
    "mischievous children",
    "poor kid",
    "smart kid",
    "street kid",
    "tween"
  ],
  "documentary_biopic": [
    "based on cartoon",
    "based on comic",
    "based on manga",
    "based on memoir or autobiography",
    "based on movie",
    "based on short story",
    "based on toy",
    "film crew",
    "filmmaking",
    "historical",
    "investigative journalism",
    "journalism",
    "nature",
    "science documentary"
  ],
  "music_dance": [
    "ballet dancer",
    "based on play or musical",
    "boy band",
    "classical music",
    "country music",
    "dance performance",
    "electronic music",
    "flamenco",
    "guitar",
    "jazz singer or musician",
    "jukebox musical",
    "k-pop",
    "music critic",
    "musician",
    "piano",
    "pop music",
    "popstar",
    "rock music",
    "saxophone",
    "singing",
    "violin"
  ],
  "sports": [
    "baseball player",
    "basketball player",
    "bowling",
    "bowling ball",
    "bowling team",
    "boxing champion",
    "boxing manager",
    "boxing trainer",
    "college american football",
    "extreme sports",
    "football (soccer)",
    "football (soccer) mom",
    "grand",
    "karate",
    "kendo",
    "kung fu",
    "kung fu master",
    "mixed martial arts (mma)",
    "national basketball association (nba)",
    "silat",
    "sport climbing",
    "sports car",
    "tournament",
    "wing chun",
    "world cup",
    "wrestling",
    "wrestling coach"
  ],
  "western": [
    "neo-western",
    "old west",
    "sheriff",
    "space western"
  ],
  "political": [
    "american revolution",
    "artistic revolution",
    "authoritarian",
    "conspiracy",
    "corrupt government",
    "fictional government agency",
    "fugue state",
    "gallipoli campaign",
    "government agency",
    "government agent",
    "government official",
    "governor",
    "internal revenue service",
    "mayoral election",
    "new york state",
    "patriotism",
    "political activism",
    "political assassination",
    "political campaign",
    "political incompetence",
    "political instability",
    "political intrigue",
    "political persecution",
    "political repression",
    "reign of terror",
    "revolution",
    "senate",
    "senator",
    "state terrorism",
    "statesman",
    "the white house",
    "thriller",
    "totalitarian regime",
    "treasury department",
    "u.s. ambassador",
    "usa politics"
  ],
  "religion_myth": [
    "arthurian mythology",
    "biblical epic",
    "christian",
    "church",
    "church service",
    "cult figure",
    "cult leader",
    "egyptian mythology",
    "evil nun",
    "jainism",
    "koran",
    "messiah",
    "moses",
    "muhammad",
    "nun",
    "pope",
    "priest",
    "religion and supernatural",
    "religious allegory",
    "religious education",
    "religious hypocrisy",
    "religious satire",
    "religious symbolism",
    "shia",
    "shia islam",
    "sikhism",
    "spiritism",
    "temple"
  ],
  "survival_disaster": [
    "avalanche",
    "environmental disaster",
    "flooding",
    "hypothermia",
    "isolated farmhouse",
    "isolated house",
    "isolated place",
    "lockdown",
    "quicksand",
    "sandstorm",
    "shipwreck",
    "snowstorm",
    "storm",
    "stranded",
    "struggle for survival",
    "survival horror",
    "survival of the fittest",
    "survival thriller",
    "trapped in burning building",
    "trapped in space",
    "wilderness"
  ],
  "travel_road": [
    "around the world",
    "book tour",
    "dimensional travel",
    "hero's journey",
    "interdimensional travel",
    "intergalactic travel",
    "oceanic expedition",
    "on the road",
    "prisoner transport",
    "route 66",
    "summer vacation",
    "train travel",
    "transport",
    "traveling by train",
    "trekking",
    "trip",
    "vacation"
  ],
  "animals_nature": [
    "animal cruelty",
    "animal horror",
    "animal human friendship",
    "animal kingdom",
    "animal lead",
    "animal sanctuary",
    "animal sidekick",
    "animal species",
    "animal testing",
    "anthropomorphic animal",
    "ape",
    "atlantic ocean",
    "attachment to nature",
    "attack",
    "bear attack",
    "bird",
    "black bear",
    "cat",
    "cat burglar",
    "crocodile",
    "dead dog",
    "deadly snake",
    "documentary",
    "dodo bird",
    "dog",
    "dog attack",
    "dog training",
    "eaten by animal",
    "elephant",
    "giant ape",
    "giant gorilla",
    "goats",
    "gorilla",
    "great white shark",
    "grizzly bear",
    "heart attack",
    "himalaya mountain range",
    "hippopotamus",
    "hot dog",
    "human animal hybrid",
    "human animal relationship",
    "human becoming an animal",
    "humpback whale",
    "hyena",
    "indian attack",
    "jungle",
    "lemur",
    "lion attack",
    "loan shark",
    "man vs nature",
    "meerkat",
    "monkey",
    "monkey warrior",
    "mountain",
    "mountain cabin",
    "mountain climbing",
    "mountain resort",
    "mountain village",
    "mutant animal",
    "ocean",
    "ocean liner",
    "octopus",
    "orangutan",
    "owl",
    "pacific  ocean",
    "pacific ocean",
    "panda",
    "parrot",
    "penguin",
    "pony",
    "primate",
    "python",
    "rabbit",
    "rain",
    "saber-toothed tiger",
    "seal (animal)",
    "shark",
    "shark cage",
    "snow",
    "stuffed animal",
    "talking animal",
    "talking cat",
    "talking dog",
    "talking to animals",
    "terrorist attack",
    "threatened ecosystem",
    "toad",
    "turns into animal",
    "violence against animals",
    "warthog",
    "wild animal",
    "woodpecker",
    "zebra"
  ],
};

export const GENERATED_NEW_BUCKETS = [
  {
    "key": "tag_people_roles",
    "needles": [
      "abused as a child",
      "accountant",
      "activist",
      "adopted child",
      "adrenaline junkie",
      "adventurer",
      "agent",
      "altar boy",
      "analyst",
      "apprentice",
      "archaeologist",
      "aristocrat",
      "artist",
      "asian woman",
      "assistant",
      "author",
      "backpacker",
      "bartender",
      "beautiful woman",
      "beauty queen",
      "billionaire",
      "bishop",
      "blackbeard",
      "blacksmith",
      "blind woman",
      "bodyguard",
      "boss",
      "botanist",
      "bouncer",
      "bounty hunter",
      "boxer",
      "boy",
      "british prime minister",
      "business tycoon",
      "businessman",
      "cadet",
      "cardinal",
      "caregiver",
      "cartoonist",
      "ceo",
      "champion",
      "chauffeur",
      "child in peril",
      "child molester",
      "child prodigy",
      "child protective services",
      "chinese girl",
      "chinese immigrant",
      "chinese woman",
      "clergyman",
      "collector",
      "commando",
      "con artist",
      "con man",
      "conductor",
      "construction worker",
      "convict",
      "corrupt politician",
      "crazy woman",
      "creator",
      "crooked politician",
      "cryptologist",
      "dead child",
      "debt collector",
      "delivery driver",
      "depressed woman",
      "desperate woman",
      "district attorney",
      "doctor",
      "double agent",
      "driver",
      "duchess",
      "duke",
      "dying man",
      "eccentric man",
      "egyptologist",
      "emperor",
      "enforcer",
      "entrepreneur",
      "escaped convict",
      "evil doctor",
      "evil man",
      "evil queen",
      "evil woman",
      "excavator",
      "famous painter",
      "farmer",
      "female agent",
      "female child abuser",
      "female fighter",
      "female mercenary",
      "female warrior",
      "feral child",
      "field agent",
      "fighter",
      "fighter pilot",
      "firefighter",
      "fisherman",
      "foster child",
      "freedom fighter",
      "gamer",
      "geologist",
      "getaway driver",
      "gigolo",
      "girl next door",
      "graduate",
      "grandmother",
      "grave digger",
      "grifter",
      "grumpy man",
      "hacker",
      "hitchhiker",
      "homeless man",
      "hunter",
      "hunter are hunted",
      "huntsman",
      "hustler",
      "immigrant",
      "industrialist",
      "informant",
      "intern",
      "inventor",
      "investigative journalist",
      "investigative reporter",
      "it professional",
      "it-expert",
      "italian immigrant",
      "jail guard",
      "janitor",
      "japanese man",
      "journalist",
      "k9 officer",
      "literary agent",
      "little boy",
      "little girl",
      "manipulative woman",
      "masseuse",
      "math professor",
      "mathematician",
      "matriarch",
      "mechanic",
      "meddling neighbor",
      "mentally handicapped man",
      "mercenary",
      "meteorologist",
      "midwife",
      "migrant worker",
      "millionaire",
      "miner",
      "missing child",
      "missionary",
      "model",
      "monk",
      "motivational speaker",
      "murderer",
      "mysterious woman",
      "neighbor",
      "neurosurgeon",
      "new neighbor",
      "news reporter",
      "newspaper man",
      "nosy neighbor",
      "novelist",
      "nurse",
      "old man",
      "one eyed man",
      "online gaming",
      "only child",
      "overweight man",
      "painter",
      "pastor",
      "patriarch",
      "peacekeeper",
      "personal assistant",
      "physicist",
      "pilot",
      "pizza boy",
      "plumber",
      "policeman",
      "politician",
      "portrait of an artist",
      "precocious child",
      "pregnant woman",
      "prehistoric man",
      "president",
      "press agent",
      "prime minister",
      "prison guard",
      "prisoner",
      "prodigy",
      "professor",
      "programmer",
      "psychiatrist",
      "psychologist",
      "psychotherapist",
      "queen",
      "realtor",
      "recruit",
      "reporter",
      "revenge murderer",
      "reverend",
      "rich woman poor man",
      "rogue agent",
      "sailor",
      "samurai",
      "scholar",
      "screenwriter",
      "security guard",
      "sergeant",
      "servant",
      "shaolin monk",
      "shepherd",
      "shooter",
      "sick child",
      "social worker",
      "stringer",
      "strong woman",
      "surgeon",
      "surveillance specialist",
      "swordsman",
      "swordswoman",
      "tabloid reporter",
      "taskmaster",
      "taxi driver",
      "teenage boy",
      "teenage girl",
      "telephone switchboard operator",
      "temporal agent",
      "therapist",
      "tough girl",
      "toy maker",
      "trainer",
      "traumatized man",
      "traumatized woman",
      "truck driver",
      "tv director",
      "tv host",
      "tv news anchor",
      "tv producer",
      "u.s. marshal",
      "undercover agent",
      "university professor",
      "venture capitalist",
      "veteran",
      "violinist",
      "waitress",
      "warlord",
      "warrior",
      "warrior woman",
      "warriors",
      "wealthy man",
      "wicked woman",
      "widow",
      "widower",
      "woman agent",
      "woman director",
      "woman in a man's world",
      "woman in peril",
      "woodcutter",
      "writer",
      "young boy",
      "young man",
      "young woman",
    ],
  },
  {
    "key": "tag_time_history",
    "needles": [
      "12th century",
      "15th century",
      "22nd century",
      "23rd century",
      "24th century",
      "5th century bc",
      "6th century",
      "african history",
      "alternate history",
      "archaeological dig",
      "archaeology",
      "archeology",
      "athenian",
      "belle epoque",
      "cavemen",
      "declaration of independence",
      "egyptology",
      "fictionalized history",
      "fourth of july",
      "german history",
      "german occupation",
      "hidden history",
      "history and legacy",
      "ice age",
      "islamic history",
      "italian history",
      "jewish history",
      "knight templars",
      "maya civilization",
      "mccarthyism",
      "old testament",
      "past history",
      "pharoah",
      "prehistory",
      "red scare",
      "revisionist history",
      "saladin",
      "social history",
      "spanish history",
      "spanish second republic (1931-39)",
      "stone age",
      "stonehenge",
      "the great seljuks",
      "the troubles (north ireland, 1966-98)",
      "turkish history",
    ],
  },
  {
    "key": "tag_identity_culture",
    "needles": [
      "afrofuturism",
      "american",
      "american abroad",
      "american dream",
      "asian american",
      "australian aboriginal",
      "black slave",
      "bohemian",
      "catholic",
      "catholicism",
      "caucasian",
      "chinese",
      "closeted homosexual",
      "east asian lead",
      "ethiopian jews",
      "female homosexuality",
      "female protagonist",
      "feminism",
      "forbidden sexuality",
      "foreigner",
      "gay theme",
      "gender roles",
      "generation z",
      "hillbilly",
      "indigenous",
      "intersex",
      "intersexuality",
      "irish-american",
      "italian american",
      "lesbian",
      "lgbt teen",
      "male homosexuality",
      "mexican american",
      "native american",
      "native hawaiian",
      "native peoples",
      "pre-teen",
      "queer loneliness",
      "sexuality",
      "transgender",
      "turkish",
      "white russian",
      "whitewashing",
      "womanhood",
    ],
  },
  {
    "key": "tag_relationship_dynamics",
    "needles": [
      "abandonment",
      "ancestor",
      "anniversary",
      "best friend",
      "best friends",
      "betrayal",
      "betrayal by friend",
      "birthday",
      "birthday present",
      "bromance",
      "brotherhood",
      "bucket list",
      "candlelight vigil",
      "chance meeting",
      "class differences",
      "class prejudice",
      "confess feelings",
      "dead parents",
      "divorced parents",
      "double life",
      "former best friend",
      "foster mom",
      "foster parents",
      "friends",
      "grandparents",
      "group of friends",
      "infidelity",
      "influential aunt or uncle",
      "life after personal tragedy",
      "marital separation",
      "missing person",
      "motherhood",
      "moving out",
      "old flame",
      "opposites attract",
      "partnership",
      "pregnancy",
      "pregnant",
      "reconnect",
      "return to hometown",
      "reunite",
      "reunited friends",
      "roommates",
      "sisterhood",
      "spanning generations",
      "stepsister",
      "survivor's guilt",
      "teenage crush",
    ],
  },
  {
    "key": "tag_health_medical",
    "needles": [
      "agoraphobia",
      "alzheimer's disease",
      "amnesia",
      "amputation",
      "amputee",
      "asperger's syndrome",
      "binge eating",
      "bipolar disorder",
      "blindness",
      "burn injury",
      "chronic pain",
      "claustrophobia",
      "clinical",
      "covid-19",
      "dehydration",
      "dental braces",
      "dentures",
      "disability",
      "disabled",
      "disabled person",
      "disease",
      "disorder",
      "down syndrome",
      "dyslexia",
      "eating disorder",
      "famous painting",
      "headache",
      "healing",
      "healing gift",
      "healing power",
      "healing process",
      "hearing voices",
      "illness",
      "insomnia",
      "knee injury",
      "lethal virus",
      "mental asylum",
      "mental breakdown",
      "mental disorders",
      "mental health",
      "mental health clinic",
      "mental illness",
      "mental institution",
      "mental link",
      "mentally challenged",
      "mentally disabled",
      "morbidly obese",
      "multiple personality disorder",
      "muscular dystrophy",
      "obesity",
      "pain medication",
      "paraplegic",
      "parasite underneath skin",
      "post-traumatic stress disorder (ptsd)",
      "prosthesis",
      "psychiatry",
      "psychology",
      "quadriplegia",
      "quadriplegic",
      "schizophrenia",
      "self-inflicted injury",
      "shock treatment",
      "short-term memory",
      "sickness",
      "spinal injury",
      "surgery",
      "terminal illness",
      "traumatized person",
      "universal cure",
      "vaccine",
      "wheelchair",
      "x-ray vision",
    ],
  },
  {
    "key": "tag_science_technology",
    "needles": [
      "amateur radio",
      "animatronic",
      "anti matter",
      "apollo program",
      "asteroid",
      "automation",
      "big tech",
      "biotech company",
      "black hole",
      "brain capacity",
      "brain implant",
      "brainiac",
      "brainwashing",
      "butterfly effect",
      "cable network",
      "cell phone",
      "change the past",
      "cloaking device",
      "communicating via phone",
      "cosmology",
      "cryonics",
      "digital world",
      "e-mail",
      "eclipse",
      "elements",
      "enterprise-e",
      "evolution",
      "experiment",
      "fusion reactor",
      "futuristic",
      "futuristic society",
      "genetics",
      "gravity",
      "hacking",
      "ham radio",
      "hard drive",
      "hidden camera",
      "high tech",
      "human brain",
      "human evolution",
      "infinite possibilities",
      "infinity",
      "internet",
      "invention",
      "laser beam",
      "lightning",
      "malfunction",
      "math genius",
      "mathematics",
      "mechanical",
      "mechanical hand",
      "medical research",
      "medical trials",
      "medicine",
      "memory manipulation",
      "meteorite",
      "mind booster",
      "mind control",
      "mind game",
      "mind parasite",
      "mind reading",
      "network",
      "nikola tesla",
      "nootropics",
      "numbers",
      "pharmaceutical lab",
      "phasing",
      "phone call",
      "phone message",
      "physics",
      "power outage",
      "prime number",
      "radio telescope",
      "radio wave",
      "radioactivity",
      "scientific research",
      "scientific study",
      "security system",
      "simulator",
      "smart phone",
      "smartphone",
      "solar eclipse",
      "solar system",
      "spacewalk",
      "speed of light",
      "supernova",
      "surveillance",
      "surveillance camera",
      "synthezoid",
      "tech company",
      "technological evolution",
      "technophobia",
      "terraforming",
      "tesla coil",
      "text messaging",
      "tracking device",
      "transhumanism",
      "transporter",
    ],
  },
  {
    "key": "tag_supernatural_myth",
    "needles": [
      "afterlife",
      "another dimension",
      "another world",
      "apparition",
      "archangel gabriel",
      "archdiocese",
      "baba yaga",
      "back from the dead",
      "belief in god",
      "chosen one",
      "day of the dead",
      "demigod",
      "draining souls",
      "dream come true",
      "dream realm",
      "dream sequence",
      "dream world",
      "dreamland",
      "dreamscape",
      "egyptian god",
      "enchant",
      "enchantress",
      "evil doll",
      "extraordinary powers",
      "folklore",
      "gnosticism",
      "goblins",
      "god king",
      "god of thunder",
      "hidden powers",
      "holy grail",
      "holy water",
      "iconography",
      "illuminati",
      "immortality",
      "king midas",
      "levitation",
      "life after death",
      "living dead",
      "lost souls",
      "lovecraftian",
      "magical",
      "magical object",
      "magical realism",
      "mermaid",
      "mexican folklore",
      "mr. hyde",
      "mystical land",
      "mythological place",
      "norwegian folklore",
      "other world",
      "ouija board",
      "pentagram",
      "personification",
      "possessed doll",
      "precognition",
      "premonition",
      "prophetic",
      "psychic",
      "reanimation",
      "soul selling",
      "soul transference",
      "spiritual community",
      "spirituality",
      "symbolism",
      "symbology",
      "wish fulfillment",
      "ying yang",
    ],
  },
  {
    "key": "tag_crime_justice",
    "needles": [
      "airplane hijacking",
      "arms deal",
      "arms dealer",
      "assassination",
      "assassination attempt",
      "beaten to death",
      "biological weapon",
      "black ops",
      "burglar",
      "buried alive",
      "cannibalism",
      "capital punishment",
      "captive",
      "captivity",
      "capture",
      "captured",
      "corrupt official",
      "counterterrorism",
      "covert agency",
      "covert missions",
      "covert operation",
      "death by poisoning",
      "death game",
      "death match",
      "death penalty",
      "death row",
      "death squads",
      "deception",
      "delinquent",
      "disappearance",
      "disavowed",
      "disguise",
      "domestic terrorism",
      "eco terrorism",
      "electric chair",
      "electrocution",
      "enslavement",
      "entrapment",
      "ex-con",
      "extortion",
      "fake death",
      "fake id",
      "false accusations",
      "false passport",
      "falsely accused",
      "fugitive",
      "held at gunpoint",
      "held captive",
      "hijacking",
      "human trafficking",
      "imprisonment",
      "interrogation",
      "jailbreak",
      "juvenile delinquent",
      "killing",
      "killing spree",
      "law and ethics",
      "mass hanging",
      "no questions asked",
      "parole board",
      "patricide",
      "pedophile",
      "pedophilia",
      "prison break",
      "prison cell",
      "prosecution",
      "public security",
      "ransom demand",
      "revenge killing",
      "revolver",
      "runaway",
      "runaway train",
      "s.w.a.t.",
      "sabotage",
      "scalping",
      "security leak",
      "self-cannibalism",
      "self-sabotage",
      "severed finger",
      "ship hijacking",
      "silencer",
      "smuggling",
      "smuggling (contraband)",
      "stabbed",
      "stakeout",
      "stalking",
      "sting operation",
      "terrorism",
      "terrorist",
      "terrorist group",
      "terrorist plot",
      "terrorist threat",
      "treason",
      "undercover",
      "undercover operation",
      "vigilantism",
      "witness elimination",
      "wrongful imprisonment",
    ],
  },
  {
    "key": "tag_war_politics",
    "needles": [
      "anarchy",
      "anc (african national congress)",
      "arbitrary law",
      "armageddon",
      "auschwitz-birkenau concentration camp",
      "ben franklin",
      "benito mussolini",
      "black panther party",
      "bundesnachrichtendienst (bnd)",
      "communism",
      "concentration camp",
      "conquest",
      "convent",
      "crusade",
      "defense industry",
      "delta force",
      "dunkirk",
      "elite forces",
      "end of the world",
      "environmental crisis",
      "evacuation",
      "evil dictator",
      "evil king",
      "evil mastermind",
      "evil tyrant",
      "fascism",
      "fighting",
      "foreign legion",
      "foreign legionaire",
      "franco regime (francoism)",
      "freemason",
      "genocide",
      "global threat",
      "holocaust (shoah)",
      "holocaust (shoah) survivor",
      "insurgence",
      "insurrection",
      "international relations",
      "jew persecution",
      "jewish ghetto",
      "mass evacuation",
      "militia",
      "ministry",
      "nazi collaborationism",
      "nazi occupation",
      "nazi train",
      "operation",
      "pacific theater",
      "pacifism",
      "peace conference",
      "peace contract",
      "peace corps",
      "peace offering",
      "power relations",
      "public figure",
      "rebellion",
      "refugee",
      "refugee camp",
      "refugee crisis",
      "resistance",
      "rise to power",
      "royalty",
      "russian occupation",
      "save humanity",
      "save the day",
      "save the world",
      "saving the world",
      "slave trade",
      "social issues",
      "soviet union",
      "ss (nazi schutzstaffel)",
      "struggle for independence",
      "teenage rebellion",
      "totalitarianism",
      "traitor",
      "tribal chief",
      "tribal customs",
      "tribal people",
      "underground fighting",
      "uniform",
      "united nations",
      "waffen ss",
      "weapons manufacturer",
      "weapons training",
      "wicked king",
      "word domination",
      "world domination",
      "world peace",
    ],
  },
  {
    "key": "tag_business_society",
    "needles": [
      "black friday",
      "boys club",
      "business rivalry",
      "business start-up",
      "consumerism",
      "contract",
      "product placement",
      "direct to video",
      "factual",
      "corporation",
      "critically bashed",
      "culture clash",
      "evil corporation",
      "failure",
      "financial crisis",
      "financial investor",
      "gentrification",
      "gig economy",
      "hostile takeover",
      "job interview",
      "management",
      "megacorporation",
      "middle class",
      "movie business",
      "new job",
      "news business",
      "one last job",
      "passed over for promotion",
      "pharmaceutical industry",
      "pop culture",
      "poverty",
      "property",
      "public image",
      "quitting a job",
      "rags to riches",
      "repayment",
      "rich snob",
      "rise and fall",
      "social commentary",
      "social media",
      "social media influencer",
      "social outcast",
      "social realism",
      "society",
      "unemployed",
      "unemployment",
      "workaholic",
      "workers' quarter",
      "working class",
    ],
  },
  {
    "key": "tag_media_entertainment",
    "needles": [
      "a arte de amar",
      "a bug's life",
      "acrobats",
      "audition",
      "auto-tuning",
      "black and white",
      "breakdance",
      "buddy film",
      "burlesque",
      "claymation",
      "comedian",
      "dancing",
      "fading star",
      "film director",
      "filming",
      "freak show",
      "game show",
      "illustrator",
      "improv group",
      "improvisation",
      "interview",
      "journal",
      "led zeppelin",
      "live broadcast",
      "live cinema",
      "live on air",
      "mona lisa (la gioconda)",
      "movie fan",
      "movie star",
      "newspaper",
      "newspaper article",
      "old hollywood",
      "panavision",
      "performance art",
      "photograph",
      "plasticine",
      "polaroid",
      "polaroid camera",
      "pop star",
      "pottery",
      "psychotronic film",
      "radio program",
      "record producer",
      "role playing game",
      "shakespeare in modern dress",
      "show business",
      "showbiz",
      "silent film star",
      "stardom",
      "steampunk",
      "tabloid",
      "talent show",
      "talk show",
      "teen movie",
      "television / tv studio",
      "theater",
      "theater audience",
      "tokusatsu",
      "tv show",
      "video game",
      "videotape",
      "vinyl record",
      "watching tv",
      "yellow press",
    ],
  },
  {
    "key": "tag_transport_travel",
    "needles": [
      "aircraft",
      "aircraft carrier",
      "airplane",
      "ambulance",
      "armored vehicle",
      "balloon",
      "bullet train",
      "bus accident",
      "cargo ship",
      "cash truck",
      "crash landing",
      "cruise ship",
      "fishing boat",
      "helicopter",
      "helicopter crash",
      "high speed",
      "highway",
      "horse and wagon",
      "horse riding",
      "horseback riding",
      "hot air balloon",
      "lifeboat",
      "modified vehicle",
      "motor vehicle",
      "motorcycle",
      "naval aviation",
      "naval battleship",
      "night bus",
      "orient express",
      "overboard",
      "parachute",
      "passenger train",
      "pickup truck",
      "porsche",
      "sailboat",
      "sailing",
      "sailing ship",
      "shinkansen",
      "shipwrecked",
      "sinking ship",
      "stagecoach",
      "steam train",
      "stunt driving",
      "stunt riding",
      "submarine",
      "subway train",
      "titanic",
      "train crash",
      "trainsurfing",
      "whaling ship",
    ],
  },
  {
    "key": "tag_nature_animals",
    "needles": [
      "ant-hill",
      "apex predator",
      "aquarium",
      "beekeepers",
      "blizzard",
      "chameleon",
      "chicken",
      "chimpanzee",
      "chipmunk",
      "clownfish",
      "cornfield",
      "crop circle",
      "dead horse",
      "endangered species",
      "extinction",
      "firefly",
      "fish out of water",
      "floating ice",
      "formiga",
      "gafanhoto",
      "giant crab",
      "giant insect",
      "giant worm",
      "giraffe",
      "glaciale",
      "grasshopper",
      "ground sloth",
      "hedgehog",
      "hibernation",
      "ice melting",
      "illegal logging",
      "illegal mining",
      "injured horse",
      "jurassic",
      "land bridge",
      "mammoth",
      "mandrill",
      "mating ritual",
      "melting ice",
      "neanderthal",
      "paleontology",
      "pelican",
      "plantation",
      "potatoes",
      "praying mantis",
      "raccoon",
      "rainstorm",
      "reindeer",
      "sand dune",
      "santa claus",
      "scuba diving",
      "skeleton",
      "snowman",
      "squirrel",
      "sunlight",
      "survivalism",
      "survivalist",
      "thunderstorm",
      "water buffalo",
      "water shortage",
      "weather",
    ],
  },
  {
    "key": "tag_objects_props",
    "needles": [
      "antidote",
      "artifact",
      "autograph",
      "bayonet",
      "bow and arrow",
      "briefcase",
      "cadaver",
      "catapult",
      "chainsaw",
      "champagne",
      "chloroform",
      "clown makeup",
      "compass",
      "crucifix",
      "flamethrower",
      "handcuffs",
      "ice cream",
      "incinerator",
      "last will and testament",
      "mysterious box",
      "nunchaku",
      "passport",
      "pay phone",
      "pyramid",
      "safe deposit box",
      "sattelite",
      "sledgehammer",
      "stashed cash",
      "stethoscope",
      "suitcase",
      "trapdoor",
      "ventriloquist's dummy",
      "wooden dummy",
    ],
  },
  {
    "key": "tag_philosophy_concepts",
    "needles": [
      "affectation",
      "allegorical",
      "allegory",
      "anthropology",
      "breaking the fourth wall",
      "metafiction",
      "self-referential",
      "voiceover",
      "narration",
      "confession",
      "coming out",
      "anthropomorphism",
      "architecture",
      "bravery",
      "celebration",
      "challenge",
      "coincidence",
      "consciousness",
      "consequences",
      "cynicism",
      "dedication",
      "deja vu",
      "determinism",
      "duality",
      "egomania",
      "existentialism",
      "forgiveness",
      "good versus evil",
      "illumination",
      "illusion",
      "imaginary",
      "imagination",
      "innocent",
      "instinct",
      "knowledge",
      "life and death",
      "life on the margin",
      "matter of life and death",
      "metaphor",
      "moral dilemma",
      "mortality",
      "objective",
      "obsession",
      "perspective",
      "philosophy",
      "prejudice",
      "questioning",
      "responsibility",
      "sociology",
      "solidarity",
      "subconscious",
      "surrealism",
      "translation",
      "worlds collide",
    ],
  },
  {
    "key": "tag_franchise_references",
    "needles": [
      "beyaz melek",
      "fantastic beasts and where to find them",
      "flying dutchman",
      "harry callahan",
      "huang feihong",
      "king ghidorah",
      "king kong",
      "romulans",
      "romulus",
      "uncharted",
      "uss enterprise-a",
      "uss reliant",
      "prequel",
      "sequel",
      "spin off",
      "reboot",
      "film remake",
      "adaptation",
      "faithful adaptation",
      "foreign language adaptation",
      "based on graphic novel",
      "based on magazine, newspaper or article",
      "based on short film",
      "based on theme park ride",
      "based on tv series",
      "based on video game",
      "retelling",
      ],
    },
  {
    "key": "tag_action_events",
    "needles": [
      "accident",
      "alternative reality",
      "amusement park",
      "annihilation",
      "archery",
      "backwards",
      "banishment",
      "barrier ice",
      "basement",
      "beauty contest",
      "bedroom",
      "behind enemy lines",
      "black mass",
      "body-swap",
      "break out",
      "breakdown",
      "bullying",
      "burgers",
      "camping",
      "carnival",
      "chancel",
      "christmas",
      "clandestine",
      "classroom",
      "climbing",
      "conference",
      "confrontation",
      "construction site",
      "contagion",
      "corrupt system",
      "crawlspace",
      "cryptozoology",
      "damsel in distress",
      "dead body",
      "death of king",
      "decipher",
      "decipherment",
      "destroy",
      "destruction",
      "displaced persons",
      "displacement",
      "doing the right thing",
      "domestic care",
      "dormitory",
      "drifting",
      "dual role",
      "dumb blonde",
      "dungeon crawling",
      "dying and death",
      "egyptian tomb",
      "elderly lady",
      "embarrasment",
      "emigrantes",
      "emigration",
      "eroticism",
      "escapade",
      "eviction",
      "evil genius",
      "evil stepmother",
      "ex special forces",
      "excavation",
      "experimental",
      "exploding ship",
      "explore",
      "explosive",
      "eye patch",
      "faithlessness",
      "fall from grace",
      "falling out window",
      "famous address",
      "farewell",
      "female hysteria",
      "fictitious country",
      "fireworks",
      "first date",
      "flesh eating",
      "fortress",
      "fortune teller",
      "free climbing",
      "free fall",
      "freed slave",
      "funeral",
      "fur trapping",
      "gambling",
      "gambling debt",
      "game developer",
      "generazioni",
      "genesis",
      "giving birth",
      "good becoming evil",
      "gorefest",
      "goth girls",
      "grandmaster",
      "grave digging",
      "halloween",
      "handshake",
      "hangman",
      "hidden civilization",
      "holiday",
      "holidays",
      "homeless",
      "hoodlum",
      "human flesh",
      "human subjugation",
      "hypnosis",
      "illusionist",
      "immigration",
      "impersonation",
      "impregnation",
      "industrial",
      "infiltration",
      "informative",
      "insanity",
      "invisible person",
      "jump scare",
      "k9 unit",
      "kindergarten",
      "labyrinth",
      "language barrier",
      "lasagna",
      "leonardo da vinci",
      "liberation",
      "locked door",
      "lost civilization",
      "manipulation",
      "mass destruction",
      "massive casualties",
      "massive explosions",
      "meditation",
      "midlife crisis",
      "mining accident",
      "misadventure",
      "misinformation",
      "monitor",
      "multiple identities",
      "multiple personality",
      "new year",
      "new year's eve",
      "one night",
      "oppression",
      "paragliding",
      "patriarchy",
      "peak oil",
      "person on fire",
      "personal growth",
      "phrogging",
      "physical training",
      "planning",
      "poker race",
      "pool table",
      "praying",
      "procedure",
      "proprietary",
      "psychotronic",
      "rampage",
      "reading people",
      "recruiting",
      "retrofuturism",
      "revelation",
      "revenge",
      "revenge motive",
      "riesen-ipod",
      "running away",
      "saving christmas",
      "scam call center",
      "scarecrow",
      "search party",
      "shaolin",
      "shelter",
      "shrinking",
      "sign languages",
      "silhouette",
      "skinning",
      "skyscraper",
      "sliding puzzle",
      "sociopath",
      "southern gothic",
      "spaceman",
      "split personality",
      "starvation",
      "stealing",
      "stolen patent",
      "strip club",
      "support group",
      "suppressed past",
      "survive",
      "swashbuckler",
      "swimming pool",
      "teenage angst",
      "teenage protagonist",
      "thanksgiving",
      "tortured genius",
      "tourism",
      "tourist trap",
      "training",
      "transformation",
      "trying to avoid making noise",
      "urban gothic",
      "whistle-blowing site",
      "wu shu",
    ],
  },
  {
    "key": "tag_mood_tone",
    "needles": [
      "darkness",
      "gloomy",
      "grim",
      "gritty",
      "ominous",
      "foreboding",
      "unsettling",
      "ghoulish",
      "surreal",
      "mysterious",
      "enigmatic",
      "suspenseful",
      "shocking",
      "bizzare"
    ]
  },
  {
    "key": "tag_redemption",
    "needles": [
      "hopeful",
      "optimism",
      "optimistic",
      "redemption",
      "rebirth",
      "new beginning",
      "overcoming fears",
      "empowerment",
      "inspirational",
      "make it happen",
      "success",
      "promise"
    ]
  },
  {
    "key": "tag_nostalgia",
    "needles": [
      "nostalgia",
      "nostalgic",
      "memories",
      "wistful",
      "reminiscent",
      "sentimental",
      "glory days"
    ]
  },
  {
    "key": "tag_absurd_irony",
    "needles": [
      "absurd",
      "whimsical",
      "playful",
      "satirical",
      "ironic",
      "irreverent",
      "witty",
      "offbeat",
      "mischievous",
      "farcical"
    ]
  },
  {
    "key": "tag_heroism",
    "needles": [
      "underdog",
      "one against many",
      "outnumbered",
      "outsider",
      "rivalry",
      "female rivalry",
      "teamwork",
      "noble sacrifice",
      "self sacrifice",
      "protection",
      "loyalty"
    ]
  },
];
